---
driver:
  name: vagrant
  username: vagrant
  customize:
    memory: 1024
    cpus: 2
    natdnsproxy1: 'off'
    natdnshostresolver1: 'off'

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.4'

platforms:
 - name: centos-6.7
   driver:
     box: bento/centos-6.7
     network:
       - ['private_network', {ip: '172.16.0.01'}]
 - name: centos-7.1
   driver:
     box: bento/centos-7.1
     network:
       - ['private_network', {ip: '172.16.0.02'}]
suites:
  - name: default
    run_list:
      - recipe[thin::default]
    attributes:


